# Generated by Django 3.1.1 on 2020-09-06 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('synopse', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('proxy_name', models.CharField(max_length=100)),
                ('poster_file', models.FileField(upload_to='uploads/poster_file')),
                ('picture_1', models.FileField(upload_to='uploads/picture_1')),
                ('picture_2', models.FileField(upload_to='uploads/picture_2')),
                ('picture_3', models.FileField(upload_to='uploads/picture_3')),
                ('youtube_link', models.CharField(max_length=200)),
                ('local_display_auth', models.BooleanField()),
                ('social_media_auth', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UniqueLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
