# Generated by Django 3.1.1 on 2020-10-03 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedddVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=100, null=True)),
                ('ytLink', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, choices=[('0', 'HomePage'), ('1', 'Webnars'), ('2', 'Mostras'), ('3', 'Premiação')], max_length=25, null=True)),
                ('synopse', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('0', 'Alunos Atuais'), ('1', 'Alunos Antigos'), ('2', 'Ór Concour')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('synopse', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('0', 'Alunos Atuais'), ('1', 'Alunos Antigos'), ('2', 'Ór Concour')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=100, region=None)),
                ('proxy_name', models.CharField(max_length=100)),
                ('poster_file', models.FileField(upload_to='uploads/poster_file')),
                ('picture_1', models.FileField(blank=True, null=True, upload_to='uploads/picture_1')),
                ('picture_2', models.FileField(blank=True, null=True, upload_to='uploads/picture_2')),
                ('picture_3', models.FileField(blank=True, null=True, upload_to='uploads/picture_3')),
                ('youtube_link', models.CharField(max_length=200)),
                ('local_display_auth', models.BooleanField()),
                ('social_media_auth', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StartDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LaunchDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempUserID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('fired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photografy', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=100)),
                ('art_design', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=100)),
                ('picture', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=100)),
                ('acting', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=100)),
                ('sound_desing', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=100)),
                ('adaptation', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.tempuserid')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.uniquelinks'),
        ),
        migrations.CreateModel(
            name='EmbedddFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('0', 'Alunos Atuais'), ('1', 'Alunos Antigos'), ('2', 'Ór Concour')], max_length=25)),
                ('valid_for', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=25)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.movie')),
            ],
        ),
    ]
