# Generated by Django 3.1.1 on 2020-10-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='participants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
