# Generated by Django 3.1.1 on 2020-09-06 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='landpage.uniquelinks'),
            preserve_default=False,
        ),
    ]
