# Generated by Django 3.1.1 on 2020-10-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0002_movie_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='acting',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='adaptation',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='art_design',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='photografy',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='sound_desing',
        ),
        migrations.AddField(
            model_name='votes',
            name='general_score',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='embedddfilm',
            name='category',
            field=models.CharField(choices=[('0', 'Mostra Kimera Filmes'), ('1', 'Mostra Convidados')], max_length=25),
        ),
        migrations.AlterField(
            model_name='embedddvideo',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'Mostra Kimera Filmes'), ('1', 'Mostra Convidados')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('0', 'Mostra Kimera Filmes'), ('1', 'Mostra Convidados')], max_length=100),
        ),
    ]
