# Generated by Django 3.1.1 on 2020-09-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0002_movie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.uniquelinks'),
        ),
    ]
