# Generated by Django 3.1.1 on 2020-09-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0004_uniquelinks_fired'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedddVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('ytLink', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=25)),
                ('synopse', models.TextField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
