# Generated by Django 3.1.1 on 2020-09-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0005_embedddvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedddvideo',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='embedddvideo',
            name='location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='embedddvideo',
            name='synopse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='embedddvideo',
            name='tittle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/picture_1'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture_2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/picture_2'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture_3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/picture_3'),
        ),
    ]
