# Generated by Django 3.1.1 on 2020-09-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0006_auto_20200907_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
