# Generated by Django 3.1.1 on 2020-09-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0007_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startdate',
            old_name='tittle',
            new_name='LaunchDate',
        ),
    ]
