# Generated by Django 3.1.1 on 2020-09-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0008_auto_20200913_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startdate',
            name='LaunchDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
