# Generated by Django 3.1.1 on 2020-09-20 15:14

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0010_auto_20200913_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUserID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('0', 'Alunos Atuais'), ('1', 'Alunos Antigos'), ('2', 'Ór Concour')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='phone',
            field=phone_field.models.PhoneField(max_length=100),
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.tempuserid')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.movie')),
            ],
        ),
    ]
