# Generated by Django 3.1.1 on 2020-09-20 16:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0011_auto_20200920_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=100, region=None),
        ),
    ]
